// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class OldMonitorScanlinesKeys
    {
        public static readonly ValueParameterKey<bool> fisheye = ParameterKeys.NewValue<bool>(false);
        public static readonly ValueParameterKey<float> scanSpeedAdd = ParameterKeys.NewValue<float>(6.0f);
        public static readonly ValueParameterKey<float> iTime = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> lineCut = ParameterKeys.NewValue<float>(0.1f);
        public static readonly ValueParameterKey<float> whiteIntensity = ParameterKeys.NewValue<float>(0.8f);
        public static readonly ValueParameterKey<float> anaglyphIntensity = ParameterKeys.NewValue<float>(0.5f);
        public static readonly ValueParameterKey<Vector3> col_r = ParameterKeys.NewValue<Vector3>(new Vector3(0.0f,1.0f,1.0f));
        public static readonly ValueParameterKey<Vector3> col_l = ParameterKeys.NewValue<Vector3>(new Vector3(1.0f,0.0f,0.0f));
    }
}
